version: 2
jobs:
  build_lint_test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: 'NPM token'
          command: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> ~/.npmrc
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run test -- --maxWorkers=2
      - run: npm run build
      - run: npm run lint
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - node_modules
workflows:
  version: 2
  build_lint_test:
    jobs:
      - build_lint_test
